-- FinBlade CCTV — Postgres schema.
--
-- GENERATED by scripts/gen_pg_ddl.py from the live SQLite schema.
-- Do not hand-edit: the previous hand-written ddl.sql drifted to five
-- tables against nine and was missing zone_live entirely.
--
-- Timestamps are DOUBLE PRECISION epoch seconds, matching what the
-- application speaks end to end. The analytics views expose a real
-- timestamptz alongside for SQL clients.
--
--   psql "$DATABASE_URL" -f services/api/ddl_pg.sql

CREATE TABLE IF NOT EXISTS alerts (
    alert_id               BIGSERIAL PRIMARY KEY,
    rule_id                TEXT,
    severity               TEXT,
    message                TEXT,
    zone_id                TEXT,
    camera_id              TEXT,
    person_ref             TEXT,
    ts                     DOUBLE PRECISION,  -- epoch seconds, UTC
    frame                  TEXT,
    kind                   TEXT,
    acknowledged_by        TEXT,
    acknowledged_at        DOUBLE PRECISION,  -- epoch seconds, UTC
    status                 TEXT DEFAULT 'OPEN',
    note                   TEXT,
    resolved_by            TEXT,
    resolved_at            DOUBLE PRECISION,  -- epoch seconds, UTC
    site_id                TEXT
);

CREATE TABLE IF NOT EXISTS cameras (
    camera_id              TEXT PRIMARY KEY,
    site_id                TEXT,
    last_seen              DOUBLE PRECISION,  -- epoch seconds, UTC
    name                   TEXT,
    state                  TEXT,
    input_fps              DOUBLE PRECISION,
    resolution             TEXT,
    dropped_frames         BIGINT,
    reconnects             BIGINT,
    loops                  BIGINT,
    frozen                 BIGINT,
    enabled                BIGINT,
    stream_url             TEXT,
    health_ts              DOUBLE PRECISION,
    sim_failure            BIGINT DEFAULT 0,
    source                 TEXT,
    people_in_view         BIGINT DEFAULT 0,
    people_in_zones        BIGINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS events (
    event_id               TEXT PRIMARY KEY,
    event_type             TEXT,
    camera_id              TEXT,
    site_id                TEXT,
    zone_id                TEXT,
    zone_from              TEXT,
    zone_to                TEXT,
    person_ref             TEXT,
    ts                     DOUBLE PRECISION,  -- epoch seconds, UTC
    frame                  TEXT,
    payload                TEXT
);

CREATE TABLE IF NOT EXISTS forwarder_cursors (
    name                   TEXT PRIMARY KEY,
    ts                     DOUBLE PRECISION NOT NULL  -- epoch seconds, UTC
);

CREATE TABLE IF NOT EXISTS reports (
    report_id              BIGSERIAL PRIMARY KEY,
    kind                   TEXT,
    generated_at           DOUBLE PRECISION,  -- epoch seconds, UTC
    from_ts                DOUBLE PRECISION,  -- epoch seconds, UTC
    to_ts                  DOUBLE PRECISION,  -- epoch seconds, UTC
    peak_occupancy         BIGINT,
    total_alerts           BIGINT,
    payload                TEXT
);

CREATE TABLE IF NOT EXISTS zone_live (
    camera_id              TEXT NOT NULL,
    zone_id                TEXT NOT NULL,
    site_id                TEXT,
    zone_name              TEXT,
    zone_type              TEXT,
    restricted             BIGINT,
    ts                     DOUBLE PRECISION,  -- epoch seconds, UTC
    occupancy              BIGINT,
    density                DOUBLE PRECISION,
    capacity_pct           DOUBLE PRECISION,
    peak_occupancy         BIGINT,
    avg_occupancy          DOUBLE PRECISION,
    trend                  TEXT,
    extra                  TEXT,
    inflow                 DOUBLE PRECISION,
    outflow                DOUBLE PRECISION,
    status                 TEXT,
    PRIMARY KEY (camera_id, zone_id)
);

CREATE TABLE IF NOT EXISTS zone_state_ts (
    id                     BIGSERIAL PRIMARY KEY,
    zone_id                TEXT,
    camera_id              TEXT,
    zone_name              TEXT,
    zone_type              TEXT,
    restricted             BIGINT,
    ts                     DOUBLE PRECISION,  -- epoch seconds, UTC
    occupancy              BIGINT,
    density                DOUBLE PRECISION,
    capacity_pct           DOUBLE PRECISION,
    peak_occupancy         BIGINT,
    avg_occupancy          DOUBLE PRECISION,
    trend                  TEXT,
    extra                  TEXT,
    inflow                 DOUBLE PRECISION,
    outflow                DOUBLE PRECISION,
    status                 TEXT,
    site_id                TEXT
);

CREATE TABLE IF NOT EXISTS zones (
    camera_id              TEXT,
    zone_id                TEXT,
    zone_name              TEXT,
    zone_type              TEXT,
    restricted             BIGINT,
    capacity_max           BIGINT,
    area_sqm               DOUBLE PRECISION,
    warning_density        DOUBLE PRECISION,
    critical_density       DOUBLE PRECISION,
    loitering_threshold_sec DOUBLE PRECISION,
    colour                 TEXT,
    enabled                BIGINT,
    normalized_polygon     TEXT,
    polygon                TEXT,
    adjacency_list         TEXT,
    updated_at             DOUBLE PRECISION,  -- epoch seconds, UTC
    PRIMARY KEY (camera_id, zone_id)
);

-- Indexes, mirrored from the SQLite schema.
CREATE INDEX IF NOT EXISTS ix_alerts_ts ON alerts(ts);
CREATE INDEX IF NOT EXISTS ix_events_ts ON events(ts);
CREATE INDEX IF NOT EXISTS ix_events_type ON events(event_type);
CREATE INDEX IF NOT EXISTS ix_reports_gen ON reports(generated_at);
CREATE INDEX IF NOT EXISTS ix_zst_zone_cam_id ON zone_state_ts(zone_id, camera_id, id);
CREATE INDEX IF NOT EXISTS ix_zst_zone_ts ON zone_state_ts(zone_id, ts);

-- The index the analytics views live on. zone_state_ts is scanned by
-- (camera_id, zone_id, ts) for every interval and window function; the
-- SQLite schema's (zone_id, ts) index does not cover the partition.
CREATE INDEX IF NOT EXISTS ix_zst_cam_zone_ts
    ON zone_state_ts (camera_id, zone_id, ts);
CREATE INDEX IF NOT EXISTS ix_events_cam_zone_ts
    ON events (camera_id, zone_id, ts);

-- TimescaleDB, if present. Optional; the views do not depend on it.
-- SELECT create_hypertable('zone_state_ts', 'ts', chunk_time_interval => 86400);
