"""Generate the Postgres schema FROM the live SQLite schema.

services/api/ddl.sql was hand-written and drifted badly: five tables against
nine, ten columns on zone_state_ts against eighteen, and no zone_live at all —
which is the table every live read goes through. Migrating onto it would have
silently lost most of the schema.

So it is generated. SqliteStore's CREATE TABLE statements are the only
authority on what this system actually stores, and they are readable from any
database file. Anything hand-maintained alongside them drifts again.

Read-only. Writes SQL to stdout or a file; touches no database.
"""
import os
import re
import sqlite3
import sys

# SQLite is loosely typed and stores what it likes; these are the affinities the
# schema actually declares, mapped to the narrowest honest Postgres type.
TYPE_MAP = {
    "INTEGER": "BIGINT",
    "REAL": "DOUBLE PRECISION",
    "TEXT": "TEXT",
    "BLOB": "BYTEA",
    "": "TEXT",
}

# Epoch-seconds columns. They stay DOUBLE PRECISION rather than becoming
# TIMESTAMPTZ: the whole application speaks epoch floats end to end, and
# converting at the storage boundary means every read converts back. The views
# expose a real timestamp alongside, which is where a SQL client wants it.
EPOCH_COLUMNS = {"ts", "last_seen", "acknowledged_at", "resolved_at",
                 "generated_at", "from_ts", "to_ts", "updated_at"}

# Tables that are SQLite bookkeeping, not ours.
SKIP = {"sqlite_sequence", "sqlite_stat1"}


def pg_type(name: str, decl: str) -> str:
    decl = (decl or "").upper()
    base = decl.split("(")[0].strip()
    if "INT" in base and name.endswith("_id") and "AUTOINCREMENT" in decl:
        return "BIGSERIAL"
    for key, out in TYPE_MAP.items():
        if key and base.startswith(key):
            return out
    if "CHAR" in base or "CLOB" in base:
        return "TEXT"
    if "DOUB" in base or "FLOA" in base:
        return "DOUBLE PRECISION"
    if "INT" in base:
        return "BIGINT"
    return "TEXT"


def generate(db: str) -> str:
    conn = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    out = [
        "-- FinBlade CCTV — Postgres schema.",
        "--",
        "-- GENERATED by scripts/gen_pg_ddl.py from the live SQLite schema.",
        "-- Do not hand-edit: the previous hand-written ddl.sql drifted to five",
        "-- tables against nine and was missing zone_live entirely.",
        "--",
        "-- Timestamps are DOUBLE PRECISION epoch seconds, matching what the",
        "-- application speaks end to end. The analytics views expose a real",
        "-- timestamptz alongside for SQL clients.",
        "--",
        "--   psql \"$DATABASE_URL\" -f services/api/ddl_pg.sql",
        "",
    ]

    tables = [r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        if r[0] not in SKIP]

    for t in tables:
        cols = list(conn.execute(f"PRAGMA table_info({t})"))
        sql = conn.execute(
            "SELECT sql FROM sqlite_master WHERE type='table' AND name=?",
            (t,)).fetchone()[0] or ""
        # (definition, trailing comment). Kept apart so the comma can be placed
        # BEFORE the comment — appending "-- epoch seconds" to the definition
        # and then joining on "," put the comma inside the comment and silently
        # produced SQL that would not parse.
        parts = []
        for _cid, name, decl, notnull, default, pk in cols:
            typ = pg_type(name, decl)
            if pk and "AUTOINCREMENT" in sql.upper() and "INT" in (decl or "").upper():
                typ = "BIGSERIAL"
            piece = f"    {name:<22} {typ}"
            if pk and len([c for c in cols if c[5]]) == 1:
                piece += " PRIMARY KEY"
            elif notnull:
                piece += " NOT NULL"
            if default is not None and "PRIMARY KEY" not in piece:
                piece += f" DEFAULT {default}"
            parts.append((piece, "epoch seconds, UTC" if name in EPOCH_COLUMNS else ""))

        composite = [c[1] for c in cols if c[5]]
        if len(composite) > 1:
            parts.append((f"    PRIMARY KEY ({', '.join(composite)})", ""))

        out.append(f"CREATE TABLE IF NOT EXISTS {t} (")
        for i, (piece, note) in enumerate(parts):
            comma = "," if i < len(parts) - 1 else ""
            out.append(f"{piece}{comma}" + (f"  -- {note}" if note else ""))
        out.append(");")
        out.append("")

    out.append("-- Indexes, mirrored from the SQLite schema.")
    for name, sql in conn.execute(
            "SELECT name, sql FROM sqlite_master WHERE type='index' "
            "AND sql IS NOT NULL ORDER BY tbl_name, name"):
        stmt = re.sub(r"\s+", " ", sql).strip()
        stmt = stmt.replace("CREATE INDEX ", "CREATE INDEX IF NOT EXISTS ")
        stmt = stmt.replace("CREATE UNIQUE INDEX ", "CREATE UNIQUE INDEX IF NOT EXISTS ")
        out.append(stmt + ";")

    out += [
        "",
        "-- The index the analytics views live on. zone_state_ts is scanned by",
        "-- (camera_id, zone_id, ts) for every interval and window function; the",
        "-- SQLite schema's (zone_id, ts) index does not cover the partition.",
        "CREATE INDEX IF NOT EXISTS ix_zst_cam_zone_ts",
        "    ON zone_state_ts (camera_id, zone_id, ts);",
        "CREATE INDEX IF NOT EXISTS ix_events_cam_zone_ts",
        "    ON events (camera_id, zone_id, ts);",
        "",
        "-- TimescaleDB, if present. Optional; the views do not depend on it.",
        "-- SELECT create_hypertable('zone_state_ts', 'ts', chunk_time_interval => 86400);",
        "",
    ]
    return "\n".join(out)


if __name__ == "__main__":
    src = sys.argv[1] if len(sys.argv) > 1 else "data/finblade.db"
    if not os.path.exists(src):
        print(f"no database at {src}", file=sys.stderr)
        raise SystemExit(1)
    text = generate(src)
    dest = sys.argv[2] if len(sys.argv) > 2 else None
    if dest:
        with open(dest, "w") as fh:
            fh.write(text)
        print(f"wrote {dest} ({len(text.splitlines())} lines)")
    else:
        print(text)
